[loggers]
keys=root,FF_Wave0

[handlers]
keys=consoleHandler

[formatters]
keys=FF_Wave0Formatter

[logger_root]
level=INFO
handlers=consoleHandler

[logger_FF_Wave0]
level=INFO
handlers=consoleHandler
qualname=FF_Wave0
propagate=0

[handler_consoleHandler]
class=StreamHandler
formatter=FF_Wave0Formatter
args=(sys.stdout,)

[formatter_FF_Wave0Formatter]
format=[%(asctime)s - %(name)s - %(levelname)s] - %(message)s - [%(pathname)s %(funcName)s %(lineno)d]
datefmt=
